"""empty message

Revision ID: 213c269d55a0
Revises: 
Create Date: 2019-10-12 15:36:00.572079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213c269d55a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('car__rental',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pickup_id', sa.Integer(), nullable=True),
    sa.Column('dropoff_id', sa.Integer(), nullable=True),
    sa.Column('company', sa.String(length=256), nullable=True),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dropoff_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['pickup_id'], ['contact.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('destination',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('flight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('departure_time', sa.DateTime(), nullable=False),
    sa.Column('eta', sa.DateTime(), nullable=False),
    sa.Column('destination', sa.String(length=256), nullable=False),
    sa.Column('departing_from', sa.String(length=256), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_id', sa.Integer(), nullable=True),
    sa.Column('destination_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['destination_id'], ['destination.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trip.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('hotel__reservation', sa.Column('breakfast_included', sa.Boolean(), nullable=True))
    op.add_column('hotel__reservation', sa.Column('cancellation_date', sa.DateTime(), nullable=True))
    op.add_column('hotel__reservation', sa.Column('check_in', sa.DateTime(), nullable=False))
    op.add_column('hotel__reservation', sa.Column('check_out', sa.DateTime(), nullable=False))
    op.add_column('hotel__reservation', sa.Column('contact_id', sa.Integer(), nullable=True))
    op.add_column('hotel__reservation', sa.Column('destination_id', sa.Integer(), nullable=True))
    op.add_column('hotel__reservation', sa.Column('refundable', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'hotel__reservation', 'destination', ['destination_id'], ['id'])
    op.create_foreign_key(None, 'hotel__reservation', 'contact', ['contact_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'hotel__reservation', type_='foreignkey')
    op.drop_constraint(None, 'hotel__reservation', type_='foreignkey')
    op.drop_column('hotel__reservation', 'refundable')
    op.drop_column('hotel__reservation', 'destination_id')
    op.drop_column('hotel__reservation', 'contact_id')
    op.drop_column('hotel__reservation', 'check_out')
    op.drop_column('hotel__reservation', 'check_in')
    op.drop_column('hotel__reservation', 'cancellation_date')
    op.drop_column('hotel__reservation', 'breakfast_included')
    op.drop_table('activity')
    op.drop_table('flight')
    op.drop_table('destination')
    op.drop_table('car__rental')
    op.drop_table('contact')
    # ### end Alembic commands ###
